Cleanup

diff --git a/git-repo-watcher b/git-repo-watcher
--- a/git-repo-watcher
+++ b/git-repo-watcher
@@ -2,26 +2,26 @@
 
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-print_separator() {
-    for i in {1..75}; do local s=$s"-"; done && echo $s
-}
+default_interval_in_seconds=5;
+default_hooks_file="$script_dir""/git-repo-watcher-hooks"
 
 print_usage() {
-    print_separator;
-    echo "NAME";
-    echo "    git-repo-watcher -- keeps a git repository in sync with its origin";
-    echo "SYNOPSIS";
-    echo "    git-repo-watcher -d <directory> [-h <hooks-file>] [-i <interval>]";
-    echo "DESCRIPTION";
-    echo "    The following options are available:";
-    echo "    -i    Interval";
-    echo "    -h    Hooks-File";
-    print_separator;
+    echo ""
+    echo "NAME"
+    echo "    git-repo-watcher -- keeps a git repository in sync with its origin"
+    echo "SYNOPSIS"
+    echo "    git-repo-watcher -d <directory> [-h <hooks-file>] [-i <interval>]"
+    echo "DESCRIPTION"
+    echo "    The following options are available:"
+    echo "    -d    The path to the git repository"
+    echo "    -i    Watch interval time in seconds (defaults to 10 seconds)"
+    echo "    -h    Custom hooks file"
+    echo ""
     exit 1;
 }
 
-while getopts ":d:i:h:" opt; do
-    case "${opt}" in
+while getopts ":d:i:h:" options; do
+    case "${options}" in
         d)
             git_repository_dir=${OPTARG};
             ;;
@@ -38,86 +38,108 @@ while getopts ":d:i:h:" opt; do
 done
 shift $((OPTIND-1))
 
+# Validating given git directory
+
 if [[ -z "${git_repository_dir}" ]]; then
-    print_usage;
+    echo -e "\nERROR: Git directory (-d) not given!" >&2;
+    print_usage
 fi
 
-if [[ ! -d "${git_repository_dir}/.git" ]]; then
-    echo "Git repository not found: '$git_repository_dir/.git'";
-    exit 1;
+if [[ ! -d "${git_repository_dir}/.git" ]] || [[ ! -r "${git_repository_dir}/.git" ]]; then
+    echo "ERROR: Git directory (-d) not found: '$git_repository_dir/.git'!" >&2
+    print_usage
 fi
 
-if [[ -z "${hooks_file}" ]]; then
-    source "$script_dir""/git-repo-watcher-hooks";
+if [[ ! -w "${git_repository_dir}" ]]; then
+    echo "ERROR: Missing write permissions for the git directory (-d): '$git_repository_dir/.git'!" >&2
+    print_usage
+fi
+
+# Validating given hook file
+
+[[ -z "${hooks_file}" ]] && hooks_file="$default_hooks_file"
+
+if [[ -f "${hooks_file}" ]] && [[ -r "${hooks_file}" ]]; then
+    source "${hooks_file}"
 else
-    if [[ -f "${hooks_file}" ]]; then
-        source ${hooks_file}
-    else
-        echo "Hooks file not found: '$hooks_file'";
-        exit 1;
-    fi
+    echo "ERROR: Hooks (-h) file not found: '$hooks_file'" >&2
+    print_usage
 fi
+
+# Validating given interval
 
 if [[ -z "$interval_in_seconds" ]]; then
-    interval_in_seconds=10
+    interval_in_seconds="$default_interval_in_seconds"
 fi
 
-pull() {
-    print_separator
-    echo "[INFO] $(date) - pulling from $upstream"
+if [[ ! "$interval_in_seconds" =~ ^[+-]?[0-9]+([.][0-9]+)?$ ]]; then
+    echo "ERROR: Interval (-i) is not a valid number: '$interval_in_seconds'" >&2
+    print_usage
+fi
+
+if (( $(echo "$interval_in_seconds < 0.1" | bc -l) )); then
+    echo "ERROR: Interval (-i) should be greater than '0.1'" >&2
+    print_usage
+fi
+
+# Executes user hooks
+#
+# $1   - Hook name
+# $2-# - Hook arguments
+hook() {
+    hook_name="$1" && shift
+    if [[ "$(type -t "$hook_name")" = "function" ]]; then
+        eval "$hook_name '$@'"
+    fi
+}
+
+# Pulls commit from remote git repository
+#
+# $1 - Git Repository name
+# $2 - Branch name
+pull_change() {
     git pull
     exit_code=$?
 
     if [ $exit_code -eq 1 ]; then
-        pull_failed "$1" "$2"
+        hook "pull_failed" "$1" "$2" "$commit_message"
     else
         commit_message=$(git log -1 --pretty=format:"%h | %an | %ad | %s")
-        change_pulled "$1" "$2" "$commit_message"
+        hook "change_pulled" "$1" "$2" "$commit_message"
     fi
-    print_separator
 }
+
+repo_name=$(basename `$git_repository_dir`)
 
 while [[ true ]]; do
 
     cd "$git_repository_dir"
 
     if [[ -f ".git/index.lock" ]]; then
-        echo '[ERROR] Git Repository is locked'\
-            ', waiting to unlock';
-        sleep 2
+        echo "ERROR: Git repository is locked, waiting to unlock" >&2
+        sleep $interval_in_seconds
         continue
     fi
 
     git fetch
 
-    branch_temp=$(\
-        git branch \
-        | sed -n -e 's/^\* \(.*\)/\1/p' \
-        | sed -e "s/^origin\///"\
-    )
+    previous_branch="$branch"
+    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p' | sed -e "s/^origin\///")
 
-    if [[ -z $branch_temp ]]; then
-        echo '[ERROR] Unable to get branch';
+    if [[ -z $branch ]]; then
+        echo "ERROR: Unable to get branch" >&2
         exit 1
     fi
 
-    repo_name=$(basename `git rev-parse --show-toplevel`)
-
-    if [[ ! -z $branch ]] && [[ $branch != $branch_temp ]]; then
-        branch_changed "$repo_name" "$branch_temp" "$branch"
+    if [[ ! -z $previous_branch ]] && [[ "$previous_branch" != "$branch" ]]; then
+        hook "branch_changed" "$repo_name" "$branch" "$previous_branch"
     fi
 
-    branch="$branch_temp"
-
-    upstream="$(\
-        git rev-parse --abbrev-ref \
-        --symbolic-full-name @{u} 2>/dev/null\
-    )"
+    upstream="$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)"
 
     # upstream was not configured
     if [[ -z "$upstream" ]]; then
-        echo '[ERROR] Upstream is not set';
-        upstream_not_set "$repo_name" "$branch"
+        hook "upstream_not_set" "$repo_name" "$branch"
         sleep $interval_in_seconds
         continue
     fi
@@ -128,17 +150,17 @@ while [[ true ]]; do
 
     if [[ -z $started ]]; then
         started=true;
-        startup "$repo_name" "$branch";
+        hook "startup" "$repo_name" "$branch"
     fi
 
-    if [[ $git_local = $git_remote ]]; then
-        no_changes "$repo_name" "$branch"
-    elif [[ $git_local = $git_base ]]; then
-        pull "$repo_name" "$branch"
-    elif [[ $git_remote = $git_base ]]; then
-        local_change "$repo_name" "$branch"
+    if [[ "$git_local" = "$git_remote" ]]; then
+        hook "no_changes" "$repo_name" "$branch"
+    elif [[ "$git_local" = "$git_base" ]]; then
+        hook "pull_change" "$repo_name" "$branch"
+    elif [[ "$git_remote" = "$git_base" ]]; then
+        hook "local_change" "$repo_name" "$branch"
     else
-        diverged "$repo_name" "$branch"
+        hook "diverged" "$repo_name" "$branch"
     fi
 
     sleep $interval_in_seconds
