Refactoring, removed daemon logic, added tests.

diff --git a/git-repo-watcher b/git-repo-watcher
--- a/git-repo-watcher
+++ b/git-repo-watcher
@@ -1,247 +1,145 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# -------------------------------------------------------------------- #
-# CONFIGURATION
-# -------------------------------------------------------------------- #
+script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-DIR_TO_SYNC_IN="test/example-repository"
-LOOP_INTERVAL_IN_SECONDS=10
-CREDENTIAL_HELPER_CACHE_IN_SECONDS=$(($LOOP_INTERVAL_IN_SECONDS+600))
-
-# -------------------------------------------------------------------- #
-# CUSTOM HANDLER
-# -------------------------------------------------------------------- #
-
-nothing_to_pull_handler() {
-    : # Do nothing
+print_seperator() {
+    for i in {1..75}; do local s=$s"-"; done && echo $s
 }
 
-local_file_change_handler() {
-    : # Do nothing
+print_usage() {
+    print_seperator;
+    echo "NAME";
+    echo "    git-repo-watcher -- keeps a git repository in sync with its origin";
+    echo "SYNOPSIS";
+    echo "    git-repo-watcher -d <directory> [-h <hooks-file>] [-i <interval>]";
+    echo "DESCRIPTION";
+    echo "    The following options are available:";
+    echo "    -i    Interval";
+    echo "    -c    Hooks-File";
+    print_seperator;
+    exit 1;
 }
 
-repo_pulled_handler() {
-    echo "[INFO] Pulled: $1"
-}
-
-repo_pull_failed_handler() {
-    echo "[ERROR] Can not pull --> Exiting: $1"
-    exit 1
-}
-
-repo_diverged_handler() {
-    echo "[ERROR] Repo diverged --> Exiting: $1"
-    exit 1
-}
-
-# -------------------------------------------------------------------- #
-
-USER_NAME=$(whoami)
-SCRIPT_NAME=`basename "$0"`
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-LOG_FILE="$SCRIPT_DIR""/""$SCRIPT_NAME"".log"
-
-# -------------------------------------------------------------------- #
-
-ABS_DIR_TO_SYNC_IN="$SCRIPT_DIR""/""$DIR_TO_SYNC_IN"
-if [ -d "$ABS_DIR_TO_SYNC_IN" ] && [ -x "$ABS_DIR_TO_SYNC_IN" ]; then
-    DIR_TO_SYNC_IN="$ABS_DIR_TO_SYNC_IN"
-fi
-
-if [ ! -d "$DIR_TO_SYNC_IN" ] || [ ! -x "$DIR_TO_SYNC_IN" ]; then
-    echo "[ERROR] Can not access directory: '$DIR_TO_SYNC_IN'"
-    exit 1
-fi
-
-# -------------------------------------------------------------------- #
-
-cd "$DIR_TO_SYNC_IN"
-if [ ! -d ".git" ]; then
-    echo "[ERROR] Not a git repository: '$DIR_TO_SYNC_IN'"
-    exit 1
-fi
-
-# -------------------------------------------------------------------- #
-
-cl-separator() {
-    for i in {1..75}; do
-        SEP=$SEP"-"
-    done && echo $SEP && SEP=""
-}
-
-# -------------------------------------------------------------------- #
-
-if [ "$#" -eq 0 ]; then
-
-cl-separator
-cat <<EOF
-USAGE: $0 [COMMAND]
-
-POSSIBLE COMMANDS:
-    start          - Start as daemon (only one instance is possible).
-    stop           - Stop the daemon.
-    status         - Check if the script is already running.
-    start nodaemon - Start without daemonizing.
-EOF
-cl-separator
-
-exit 1
-fi
-
-# -------------------------------------------------------------------- #
-
-START=false
-STOP=false
-STATUS=false
-DAEMON=true
-
-until [ -z "$1" ]; do
-    if   ([ "$1" == "start"    ]); then
-        START=true
-    elif ([ "$1" == "stop"     ]); then
-        STOP=true
-    elif ([ "$1" == "status"   ]); then
-        STATUS=true
-    elif ([ "$1" == "nodaemon" ]); then
-        DAEMON=false
-    fi
-    shift
+while getopts ":d:i:c:" opt; do
+    case "${opt}" in
+        d)
+            git_repository_dir=${OPTARG};
+            ;;
+        h)
+            hooks_file=${OPTARG};
+            ;;
+        i)
+            interval_in_seconds=${OPTARG};
+            ;;
+        *)
+            print_usage;
+            ;;
+    esac
 done
+shift $((OPTIND-1))
 
-# -------------------------------------------------------------------- #
+if [[ -z "${git_repository_dir}" ]]; then
+    print_usage;
+fi
+
+if [[ ! -d "${git_repository_dir}/.git" ]]; then
+    echo "Git repository not found: '$git_repository_dir/.git'";
+    exit 1;
+fi
+
+if [[ -z "${hooks_file}" ]]; then
+    source "$script_dir""/git-repo-watcher-hooks";
+else
+    if [[ -f "${hooks_file}" ]]; then
+        source ${hooks_file}
+    else
+        echo "Hooks file not found: '$hooks_file'";
+        exit 1;
+    fi
+fi
+
+if [[ -z "$interval_in_seconds" ]]; then
+    interval_in_seconds=10
+fi
 
 pull() {
-    cl-separator
-    echo "[INFO] $(date) - pulling from $UPSTREAM"
-    cl-separator
-    git pull origin $BRANCH_TO_SYNC
-    RETURN_CODE=$?
-    cl-separator
+    print_seperator
+    echo "[INFO] $(date) - pulling from $upstream"
+    git pull
+    exit_code=$?
 
-    COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-    ENVIRONMENT="[$REPO_NAME | $BRANCH_TO_SYNC | '$COMMIT_MESSAGE']"
-
-    if [ $RETURN_CODE -eq 1 ]; then
-        repo_pull_failed_handler "$ENVIRONMENT"
+    if [ $exit_code -eq 1 ]; then
+        pull_failed "$1" "$2"
     else
-        repo_pulled_handler "$ENVIRONMENT"
+        commit_message=$(git log -1 --pretty=oneline)
+        change_pulled "$1" "$2" "$commit_message"
     fi
-
-    cl-separator
+    print_seperator
 }
 
-# -------------------------------------------------------------------- #
+while [[ true ]]; do
 
-watch-git-repo() {
-    while [[ true ]]; do
+    cd "$git_repository_dir"
 
-        cd "$DIR_TO_SYNC_IN"
-
-        if [ -f ".git/index.lock" ]; then
-            echo '[ERROR] Git Repository is locked, waiting to unlock';
-            sleep 2
-            continue
-        fi
-
-        git fetch
-
-        if [ -z "$BRANCH_TO_SYNC" ]; then
-            BRANCH_TO_SYNC=$(\
-                git branch \
-                | sed -n -e 's/^\* \(.*\)/\1/p' \
-                | sed -e "s/^origin\///"\
-            )
-            echo "[INFO] $(date) - Starting to watch ($BRANCH_TO_SYNC)"
-        fi
-
-        REFS=""
-        UPSTREAM="$(\
-            git rev-parse --abbrev-ref \
-            --symbolic-full-name @{u} 2>/dev/null\
-        )"
-
-        # upstream was not configured
-        if [ -z "$UPSTREAM" ]; then
-            UPSTREAM="origin/$BRANCH_TO_SYNC"
-            REFS="refs/heads/"
-        fi
-
-        GIT_LOCAL=$(git rev-parse HEAD)
-        GIT_REMOTE=$(git rev-parse "$REFS""$UPSTREAM")
-        GIT_BASE=$(git merge-base HEAD "$REFS""$UPSTREAM")
-        REPO_NAME=$(basename `git rev-parse --show-toplevel`)
-        ENVIRONMENT="[$REPO_NAME | $BRANCH_TO_SYNC]"
-
-        if [ $GIT_LOCAL = $GIT_REMOTE ]; then
-            nothing_to_pull_handler "$ENVIRONMENT"
-        elif [ $GIT_LOCAL = $GIT_BASE ]; then
-            pull
-        elif [ $GIT_REMOTE = $GIT_BASE ]; then
-            local_file_change_handler "$ENVIRONMENT"
-        else
-            repo_diverged_handler "$ENVIRONMENT"
-        fi
-
-        sleep $LOOP_INTERVAL_IN_SECONDS
-    done
-}
-
-if [ "$STATUS" = true ] || ([ "$START" = false ] && [ "$STOP" = false ]); then
-    cl-separator
-    ps aux | grep "$SCRIPT_NAME start" | grep -v "grep $SCRIPT_NAME" | \
-        grep -v " $$ "
-    RETURN_CODE=$?
-    if [ $RETURN_CODE -eq 0 ];then
-        echo "--> Already running"
-    else
-        echo "Not running"
+    if [[ -f ".git/index.lock" ]]; then
+        echo '[ERROR] Git Repository is locked'\
+            ', waiting to unlock';
+        sleep 2
+        continue
     fi
-    cl-separator
-    exit 0
-fi
 
-if $STOP ; then
-    cl-separator
-    ps aux | grep "$SCRIPT_NAME start" | grep -v "grep $SCRIPT_NAME" | \
-        grep -v " $$ "
-    RETURN_CODE=$?
-    if [ $RETURN_CODE -eq 0 ];then
-        echo "Killing $SCRIPT_NAME"
-        pkill -f "$SCRIPT_NAME start"
-    else
-        echo -e 'Not running'
-    fi
-    cl-separator
-    exit 0
-fi
-
-if $START ; then
-    cl-separator
-    ps aux | grep "$SCRIPT_NAME start" | grep -v "grep $SCRIPT_NAME" | \
-        grep -v " $$ " && cl-separator && \
-        echo -e '\n↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑\nAlready running!\n' && exit 1
-
-    cd "$DIR_TO_SYNC_IN"
-    git config --global credential.helper \
-        "cache --timeout=$CREDENTIAL_HELPER_CACHE_IN_SECONDS"
     git fetch
 
-    RETURN_CODE=$?
-    if [ $RETURN_CODE -eq 1 ];then
-        echo "Wrong password -> Exiting"
+    branch_temp=$(\
+        git branch \
+        | sed -n -e 's/^\* \(.*\)/\1/p' \
+        | sed -e "s/^origin\///"\
+    )
+
+    if [[ -z $branch_temp ]]; then
+        echo '[ERROR] Unable to get branch';
         exit 1
     fi
 
-    if $DAEMON ; then
-        echo "$(date) - Starting daemon"
-        cl-separator
-        ( watch-git-repo )  >> "$LOG_FILE" &
-        disown
-    else
-        watch-git-repo
+    repo_name=$(basename `git rev-parse --show-toplevel`)
+
+    if [[ ! -z $branch ]] && [[ $branch != $branch_temp ]]; then
+        branch_changed "$repo_name" "$branch_temp" "$branch"
     fi
 
-    exit 0
-fi
+    branch="$branch_temp"
 
-# -------------------------------------------------------------------- #
+    upstream="$(\
+        git rev-parse --abbrev-ref \
+        --symbolic-full-name @{u} 2>/dev/null\
+    )"
+
+    # upstream was not configured
+    if [[ -z "$upstream" ]]; then
+        echo '[ERROR] Upstream is not set';
+        upstream_not_set "$repo_name" "$branch"
+        sleep $interval_in_seconds
+        continue
+    fi
+
+    git_local=$(git rev-parse @)
+    git_remote=$(git rev-parse "$upstream")
+    git_base=$(git merge-base @ "$upstream")
+
+    if [[ -z $started ]]; then
+        started=true;
+        startup "$repo_name" "$branch";
+    fi
+
+    if [[ $git_local = $git_remote ]]; then
+        no_changes "$repo_name" "$branch"
+    elif [[ $git_local = $git_base ]]; then
+        pull "$repo_name" "$branch"
+    elif [[ $git_remote = $git_base ]]; then
+        local_change "$repo_name" "$branch"
+    else
+        diverged "$repo_name" "$branch"
+    fi
+
+    sleep $interval_in_seconds
+done
